name: NIFTY
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
dependencies:
  - python
  - ipython
  - numpy
  - tqdm
  - scipy
  - astropy
  - matplotlib
  - scikit-learn
  - emcee
  - corner
  - xarray
  - h5netcdf
  - h5py
  - pip
  - pip:
      - astro-sedpy
